### ISSUE TITLE
Having incorrect ids after reindexing

### ISSUE THREAD

**Issue by nasospsa** [flying-sphinx/flying-sphinx#18]
ActiveRecord::RecordNotFound (Couldn't find all `Table` with 'column': (........) (found 9 results, but was looking for 10))

I have run regenerate, rebuild

But the problem persists. It has one more id inside the index table, which either deleted or simply never existed.

Can't reproduce locally

**Comment by pat** [comment]
Hi Nasos

Firstly, if you'd like to discuss the specifics of your app in private, I recommend creating a ticket at https://support.flying-sphinx.com. But from a general perspective: can you share the index definition of the model in question, and the search query you're running that's returning the extra result? If you can share the Heroku app name as well, I'll see whether the Flying Sphinx servers have any clues.

Kind regards,

Pat
